// Java class org.firescape.go.firescape.Firescape is a proxy for talking to a Go program.
//   gobind -lang=java -javapkg=org.firescape.go firescape
//
// File is generated by gobind. Do not edit.
package org.firescape.go.firescape;

import go.Seq;

public abstract class Firescape {
    static {
        Seq.touch(); // for loading the native library
        _init();
    }
    
    private Firescape() {} // uninstantiable
    
    // touch is called from other bound packages to initialize this package
    public static void touch() {}
    
    private static native void _init();
    
    
    
}
