// JNI function headers for the Go <=> Java bridge.
//   gobind -lang=java -javapkg=org.firescape.go firescape
//
// File is generated by gobind. Do not edit.

#ifndef __Firescape_H__
#define __Firescape_H__

#include <jni.h>

extern jclass proxy_class_firescape_GoPlayer;
extern jmethodID proxy_class_firescape_GoPlayer_cons;
#endif
