// Java class go.error is a proxy for talking to a Go program.
//   gobind -lang=java -javapkg=org.firescape.go 
//
// File is generated by gobind. Do not edit.
package go;

import go.Seq;

public interface error {
    public String error();
    
}

